### get all cellphones
GET http://localhost:5000/allTechno/cellphones/cel.precio ASC

### get cellphone by id
GET http://localhost:5000/allTechno/cellphones/c3d6fe5c-1885-11ef-a2c8-d85ed3ffda3c

### create cellphone
POST http://localhost:5000/allTechno/cellphones
Content-Type: application/json

{
    "modelo" : "Redmi note 12s",
    "bateria" : 5000,
    "procesador" : "MediaTek Helio G96",
    "camaraFrontal" : 12,
    "camaraPosterior" : 108,
    "resolucion" : "2400 x 1080",
    "huella" : "En panel posterior",
    "almacenamiento" : 256,
    "ram" : 8,
    "precio" : 999.900,
    "colores" : "azul, verde, negro"
}

### modify cellphone
PATCH http://localhost:5000/allTechno/cellphones/id

Content-Type: application/json

{
    "bateria" : 5000,
    "camaraFrontal" : 12,
    "camaraPosterior" : 108,
    "colores" : "azul, verde, negro" 
}

### delete cellphone
DELETE http://localhost:5000/allTechno/cellphones/id