### get all power supplies
GET http://localhost:5000/allTechno/powerSupplies

### get power supply by id
GET http://localhost:5000/allTechno/powerSupplies/id

### create power supply
POST http://localhost:5000/allTechno/powerSupplies

Content-Type: application/json

{
    
}


### modify power supply
PATCH http://localhost:5000/allTechno/powerSupplies/id

Content-Type: application/json

{

}

### delete power supply
DELETE http://localhost:5000/allTechno/powerSupplies/id