### get all laptops
GET http://localhost:5000/allTechno/laptops

### get laptop by id
GET http://localhost:5000/allTechno/laptops/c3d789c7-1885-11ef-a2c8-d85ed3ffda3c

### create laptop
POST http://localhost:5000/allTechno/laptops

Content-Type: application/json

{
    "marca": "Apple",
    "modelo": "MacBook Pro 16",
    "procesador": "Apple M1 Pro",
    "grafica": "Apple M1 Pro GPU",
    "resolucion": "3456 x 2234 pixels",
    "tamañoPantalla": 16,
    "almacenamiento": 2048,
    "ram": 32,
    "precio": 5000000,
    "colores": "Gris Espacial, Plata"
}

### modify laptop
PATCH http://localhost:5000/allTechno/laptops:id

Content-Type: application/json

{
    "procesador": "Apple M1 Pro",
    "grafica": "Apple M1 Pro GPU",
    "ram": 32,
    "precio": 5000000,
}

### delete laptop
DELETE http://localhost:5000/allTechno/laptops:id