### get all rams
GET http://localhost:5000/allTechno/ram

### get ram by id
GET http://localhost:5000/allTechno/ram/id

### create ram
POST http://loacalhost:5000/localhost:5000/allTechno/ram

Content-Type: application/json

{

}

### modify ram
PATCH http://localhost:5000/localhost:5000/allTechno/ram/id

Content-Type: application/json

{

}

DELETE http//:localhost:5000/allTechno/ram/id